# Generated by Django 5.1 on 2024-08-18 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='block',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2')], default='A1', max_length=10, verbose_name='Блок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('new', 'Новый'), ('used', 'Использованный')], max_length=20, verbose_name='Состояние товара'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.post')),
            ],
        ),
    ]
