# Generated by Django 5.1 on 2024-08-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(max_length=9, verbose_name='Стоимость товара'),
        ),
    ]
