# Generated by Django 5.1 on 2024-08-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость товара'),
        ),
    ]
