# Generated by Django 5.1 on 2024-10-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявлении'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Личный Профиль', 'verbose_name_plural': 'Личные Профили'},
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.FileField(upload_to='post_images/'),
        ),
    ]
