# Generated by Django 5.1 on 2024-08-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('new', 'Новый'), ('used', 'Used')], default='new', max_length=20, verbose_name='Состояние товара'),
            preserve_default=False,
        ),
    ]
