# Generated by Django 5.1 on 2024-08-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_postimage_is_primary_alter_post_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='images',
            new_name='image',
        ),
    ]
