# Generated by Django 5.1 on 2024-08-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_postimage_image_favposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('books', 'books'), ('electronics', 'electronics'), ('furniture', 'furniture'), ('clothing', 'clothing'), ('others', 'others')], default='others', max_length=20, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
