# Generated by Django 5.1 on 2024-08-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_post_category_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
